version: "3.8"
services:
  casssio-ai-backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - OPENAI_TOKEN=${OPENAI_TOKEN}  

  casssio-ai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - casssio-ai-backend
